name: 'bike_share_dbt'
version: '1.0'
config-version: 2

profile: 'bike_share_dbt'

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

models:
  bike_share_dbt:

    cds:
      +schema: CDS
      +tags: ["cds"]
      +materialized: view

    dds:
      +schema: DDS
      +tags: ["dds"]
      +materialized: table

    ids:
      +schema: IDS
      +tags: ["ids"]
      +materialized: table